### ISSUE TITLE
Pulling docker image via CLI gives "denied: denied" response

### ISSUE THREAD

**Issue by JamesAlexanderHill** [muchobien/pocketbase-docker#3]
when running: `docker pull ghcr.io/muchobien/pocketbase:latest`

I get the following response:
Error response from daemon: Head "https://ghcr.io/v2/muchobien/pocketbase/manifests/latest": denied: denied

**Comment by konsila** [comment]
I’m getting the same error with pulling via “watchtower”. Haven had this problem before!

**Comment by JamesAlexanderHill** [comment]
Solution:
1. log out of ghcr.io with `docker logout ghcr.io`
2. Create a new Personal Access Token following these steps: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-with-a-personal-access-token-classic
3. cleanup any unused PAT's if they are now not being used
4. Pull your docker image as normal
